// CategoryTypes
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY'
export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR'

// SubCategoryTypes
export const CREATE_SUBCATEGORY = 'CREATE_SUBCATEGORY'
export const GET_SUBCATEGORY_ERROR = 'GET_SUBCATEGORY_ERROR'
export const GET_SUBCATEGORY_BY_CATEGORY = 'GET_SUBCATEGORY_BY_CATEGORY'


// BrandTypes
export const GET_ALL_BRAND = 'GET_ALL_BRAND'
export const CREATE_BRAND = 'CREATE_BRAND'
export const GET_BRAND_ERROR = 'GET_BRAND_ERROR'

// ProductsTypes

export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR'
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
