// CategoryTypes
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY'
export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR'
export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY'

// SubCategoryTypes
export const CREATE_SUBCATEGORY = 'CREATE_SUBCATEGORY'
export const GET_SUBCATEGORY_ERROR = 'GET_SUBCATEGORY_ERROR'
export const GET_SUBCATEGORY_BY_CATEGORY = 'GET_SUBCATEGORY_BY_CATEGORY'


// BrandTypes
export const GET_ALL_BRAND = 'GET_ALL_BRAND'
export const CREATE_BRAND = 'CREATE_BRAND'
export const GET_BRAND_ERROR = 'GET_BRAND_ERROR'
export const GET_ONE_BRAND = 'GET_ONE_BRAND'

// ProductsTypes

export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR'
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCTS'
export const GET_SPECIFIC_PRODUCTS = 'GET_SPECIFIC_PRODUCTS'
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS'


// Auth Types

export const CREATE_NEW_USER = 'CREATE_NEW_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const GET_USER_DATA = 'GET_USER_DATA'
export const LOGOUT = 'LOGOUT'
export const FORGET_PASSWORD = 'FORGET_PASSWORD'
export const VERIFY_RESET_CODE = 'VERIFY_RESET_CODE'
export const RESET_PASSWORD = 'RESET_PASSWORD'

// Review Types

export const CREATE_REVIEW = 'CREATE_REVIEW'
export const GET_REVIEW_ERROR = 'GET_REVIEW_ERROR'
export const GET_ALL_REVIEWS_ON_PRODUCT = 'GET_ALL_REVIEWS_ON_PRODUCT'


